### ISSUE TITLE
Passing in Headers from the Nimbus SDK into the Go request

### ISSUE THREAD

**Issue by marcsantiago** [adsbynimbus/nimbus-openrtb#14]
The Nimbus SDK is starting to send headers so that Nimbus Server can stat SDK versions being used by publishers. I have two different approaches for passing through this data. 1 is a non breaking change and the other is a breaking change. The non breaking change allows more flexibility by also more room for error by the implementer. Still I wanted to discuss both methods to get opinions on preferences. 

**Method 1:** (Non breaking change) adds a method that allows chain calling to pass in the Incoming Request object before calling connivence POST methods

```go
func (d *Driver) GetNimbusHeadersFromRequest(r *http.Request) *Driver {
	d.mu.Lock()
	d.headers = r.Header
	d.mu.Unlock()
	return d
}

// PostNimbus sends a POST request to Nimbus
func (d *Driver) PostNimbus(body io.Reader) (*http.Response, error) {
	req, err := http.NewRequest(http.MethodPost, d.Endpoint, body)
	if err != nil {
		return nil, err
	}

	d.mu.RLock()
	req.Header = d.headers
	d.mu.Unlock()

	req.Header.Set("Content-Type", "application/json; charset=utf-8")
	req.Header.Set("x-openrtb-version", "2.5")
	return d.Client.Do(req)
}
```

usage example

```go
driver.GetNimbusHeadersFromRequest(incomingRequest).PostNimbusTwoFiveRequestWithContext(ctx, requestBody)
```

**Method 2:** 

Update the All method signatures and interfaces to pass in the incoming request.Header object

```go
func (d *Driver) PostNimbus(body io.Reader, headers http.Header) (*http.Response, error) {
	req, err := http.NewRequest(http.MethodPost, d.Endpoint, body)
	if err != nil {
		return nil, err
	}

	
	req.Header = headers
	req.Header.Set("Content-Type", "application/json; charset=utf-8")
	req.Header.Set("x-openrtb-version", "2.5")
	return d.Client.Do(req)
}
```

**Comment by Jasrags** [comment]
Method 3: Use the option pattern
```
func WithHeaders(headers http.Header) Option {
	return func(o *Options) {
		o.Headers = headers
	}
}

func (d *Driver) PostNimbus(body io.Reader, options ...Option) (*http.Response, error) 

d.PostNimbus(body, WithHeaders(r.Headers))
```
This would allow for keeping the method signature static but allow for future optional features. It also is easier to test than method 1 and does not make headers required like method 2.

**Comment by marcsantiago** [comment]
@Jasrags I was just giving Method 3 some more thought, can `WithHeaders ` be racey, what if the client is using multiple versions of the Nimbus SDK. `o *Options` mutates the Driver object in flight, which was globally created. It is worth while adding a mutex guard in your opinion?

**Comment by marcsantiago** [comment]
To scope the optionals to just mutate the locally scoped Request object I propose the following

```go
// WithHeaders allows the caller to mutate and add headers to the new out going Nimbus request
func WithHeaders(headers http.Header) func(*http.Request) {
	return func(r *http.Request) {
		r.Header = headers
	}
}

func (d *Driver) PostNimbus(body io.Reader, options ...func(*http.Request)) (*http.Response, error) 

d.PostNimbus(body, WithHeaders(r.Headers))
```

In this way we can remove potential data races

**Comment by Jasrags** [comment]
`...func(*http.Request)` would lock you into the options only being request based, but yeh that's the best approach for function scoped options.

**Comment by marcsantiago** [comment]
I think it's okay, in terms of options on Driver, that support was added initially
`func NewNimbusDriver(endpoint string, options ...func(*Driver)) *Driver` and I can't think of anything else a request to Nimbus would need. Though if more things were needed we'd probably bump to a major version and make some breaking changes
